# -*- coding: utf-8 -*-
"""Cardshare_Telegram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3DluvnH_ozN6699CqlnZec2yTDIXv1Q
"""

import os
import re
import unicodedata
import requests
import asyncio
from telethon import TelegramClient
from telethon.sessions import StringSession

# Configuración desde Secrets de GitHub
API_ID = int(os.getenv('API_ID'))
API_HASH = os.getenv('API_HASH')
SESSION_STR = os.getenv('SESSION_STR')
CHANNEL_ID = 'NewcamdCccamIptv'

CURRENT_URL = 'http://redworld.pro:8880/get.php?username=jhon670&pasword=eMwQGD7QrzBk&type=m3u_plus&output=ts'
#'http://zeurope.xyz:8080/get.php?username=EshkaAytos&password=AytosEshka&type=m3u_plus&output=ts'
#'http://redworld.pro:8880/get.php?username=jhon670&pasword=eMwQGD7QrzBk&type=m3u_plus&output=ts'

REQUISITOS_SERIES = ['fantastico', 'magnificos', 'pantera rosa']
REQUISITOS_VOD = ['rocky', 'volver al futuro', 'shrek']
REQUISITOS_LIVE = ['24/7']

def extraer_credenciales(url):
    host = re.search(r'(http[s]?://[^/]+)', url)
    user = re.search(r'username=([^&]+)', url)
    pwd = re.search(r'pas?sword=([^&]+)', url)
    if host and user and pwd:
        return host.group(1), user.group(1), pwd.group(1)
    return None, None, None

# Definimos unos headers globales simulando ser un navegador Chrome moderno en Windows
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    'Accept': 'application/json, text/javascript, */*; q=0.01',
    'Accept-Language': 'es-ES,es;q=0.9,en;q=0.8',
    'Connection': 'keep-alive'
}

def quitar_tildes(texto):
    """Elimina tildes y diacríticos de un texto para hacer búsquedas exactas."""
    return ''.join(c for c in unicodedata.normalize('NFD', texto) if unicodedata.category(c) != 'Mn')

def validar_calidad_servidor(host, user, pwd):
    """Verifica el contenido ignorando tildes y mayúsculas."""
    try:
        r_live = requests.get(f"{host}/player_api.php?username={user}&password={pwd}&action=get_live_streams", headers=HEADERS, timeout=15)
        r_series = requests.get(f"{host}/player_api.php?username={user}&password={pwd}&action=get_series", headers=HEADERS, timeout=15)
        r_vod = requests.get(f"{host}/player_api.php?username={user}&password={pwd}&action=get_vod_streams", headers=HEADERS, timeout=15)

        if all(r.status_code == 200 for r in [r_live, r_series, r_vod]):
            # Aplicamos .lower() para mayúsculas y quitar_tildes() para los acentos
            contenido_live = quitar_tildes(str(r_live.json()).lower())
            contenido_series = quitar_tildes(str(r_series.json()).lower())
            contenido_vod = quitar_tildes(str(r_vod.json()).lower())

            tiene_247 = any(req in contenido_live for req in REQUISITOS_LIVE)
            tiene_clasicos = any(req in contenido_series for req in REQUISITOS_SERIES)
            tiene_peliculas = any(req in contenido_vod for req in REQUISITOS_VOD)

            contenido_total = contenido_live + contenido_series + contenido_vod
            tiene_etiqueta_latina = any(etiqueta in contenido_total for etiqueta in ['latino', 'espanol']) # Nota: busco 'espanol' sin la ñ por el filtro

            if tiene_247 and tiene_clasicos and tiene_peliculas and tiene_etiqueta_latina:
                return True
    except:
        pass
    return False

async def main():
    host, user, pwd = extraer_credenciales(CURRENT_URL)

    print(f"Verificando salud y contenido del servidor actual: {host}...")

    # Usamos la MISMA función de validación API para el servidor actual
    # Esto evita intentar descargar el .m3u pesado y ser bloqueado
    if host and user and pwd and validar_calidad_servidor(host, user, pwd):
        print("✅ El servidor actual funciona a nivel de API y mantiene el contenido. No es necesario reemplazarlo.")
        return

    # Si la API no responde o ya no tiene el contenido, entonces sí buscamos reemplazo
    print("❌ El servidor actual falló la conexión API o perdió el contenido. Iniciando búsqueda...")

    async with TelegramClient(StringSession(SESSION_STR), API_ID, API_HASH) as client:
        async for msg in client.iter_messages(CHANNEL_ID, limit=100):
            if not msg.text: continue

            urls = re.findall(r'(http[s]?://\S+get\.php\?username=\S+)', msg.text)

            for url_cand in urls:
                c_host, c_user, c_pwd = extraer_credenciales(url_cand)
                if not c_host: continue

                print(f"Analizando candidato: {c_host}...", end=" ")
                if validar_calidad_servidor(c_host, c_user, c_pwd):
                    nueva_url = f"{c_host}/get.php?username={c_user}&password={c_pwd}&type=m3u_plus&output=ts"
                    print(f"¡ENCONTRADO! cumple con 24/7, Series Clásicas y VOD.")
                    print(f"\n🚀 NUEVA URL PARA TU CONFIGURACIÓN:\n{nueva_url}")
                    return
                else:
                    print("No cumple requisitos.")
  # 4. En Colab, ejecutamos directamente con await
if __name__ == '__main__':
    asyncio.run(main())
