# -*- coding: utf-8 -*-
"""MasterLists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYezRYzUBrz9fc6oikIVT0QEzJjsKOXK
"""

# 1. Instalamos las herramientas
!pip install thefuzz python-Levenshtein requests

import requests
from thefuzz import process, fuzz
import re

# 2. El Robot descarga sus "Diccionarios de nombres" (EPG)
def obtener_nombres_maestros():
    urls = [
        "https://epgshare01.online/epgshare01/epg_ripper_CO1.txt",
        "https://epgshare01.online/epgshare01/epg_ripper_ALL_SOURCES1.txt"
    ]
    maestro = []
    print("⏳ Descargando diccionarios de nombres...")
    for url in urls:
        try:
            r = requests.get(url, timeout=10)
            # Separamos cada línea y evitamos las vacías
            nombres = [linea.strip() for linea in r.text.split('\n') if linea.strip()]
            maestro.extend(nombres)
        except:
            print(f"❌ No pude descargar de: {url}")

    # Quitamos duplicados para que el robot sea más rápido
    return list(set(maestro))

NOMBRES_MAESTROS = obtener_nombres_maestros()
print(f"✅ Robot listo. Aprendí {len(NOMBRES_MAESTROS)} nombres de canales.")

# 3. EL INPUT: Aquí es donde tú le hablas al robot
print("\n--- CONFIGURACIÓN DE TU LISTA ---")
entrada_usuario = input("Pega aquí tus enlaces m3u (separados por coma si son varios): ")
# Convertimos el texto en una lista de direcciones reales
SERVIDORES_M3U = [s.strip() for s in entrada_usuario.split(',') if s.strip()]

print(f"\n🚀 El robot tiene {len(SERVIDORES_M3U)} servidores para revisar.")

def extraer_canales(servidores):
    lista_candidatos = []
    print("🕵️ Buscando canales en los servidores...")

    for url in servidores:
        try:
            # El robot toca la puerta del servidor
            respuesta = requests.get(url, timeout=15)
            lineas = respuesta.text.split('\n')

            canal_actual = None
            for i in range(len(lineas)):
                linea = lineas[i].strip()

                # Si la línea empieza con #EXTINF, ahí está el nombre
                if linea.upper().startswith("#EXTINF"):
                    # Extraemos el nombre que viene después de la última coma
                    nombre = linea.split(',')[-1].strip()
                    # La dirección (URL) suele estar en la siguiente línea
                    if i + 1 < len(lineas):
                        url_canal = lineas[i+1].strip()
                        if url_canal.startswith("http"):
                            lista_candidatos.append({
                                "nombre_original": nombre,
                                "url": url_canal
                            })
            print(f"✅ Leídos los canales de: {url}")
        except:
            print(f"❌ No pude entrar al servidor: {url}")

    return lista_candidatos

# Ejecutamos la búsqueda
TODOS_LOS_CANALES = extraer_canales(SERVIDORES_M3U)
print(f"\n📦 ¡Listo! El robot encontró {len(TODOS_LOS_CANALES)} canales en total.")
print("Ejemplo del primer canal encontrado:", TODOS_LOS_CANALES[0] if TODOS_LOS_CANALES else "Ninguno")

import xml.etree.ElementTree as ET
import gzip

def construir_mapeo_categorias():
    # El robot va a usar el archivo XML que mencionaste en tu referencia
    url_epg = "https://epgshare01.online/epgshare01/epg_ripper_CO1.xml.gz"
    print("🧠 El robot está estudiando el EPG para aprender categorías...")

    mapping = {}

    try:
        response = requests.get(url_epg, stream=True)
        with gzip.open(response.raw, 'rb') as f:
            # Leemos el XML (esto es como leer el manual oficial de la TV)
            context = ET.iterparse(f, events=('end',))
            for event, elem in context:
                if elem.tag == 'channel':
                    # Sacamos el nombre del canal
                    nombre = elem.find('display-name').text if elem.find('display-name') is not None else None
                    # Intentamos buscar su categoría en el XML si existe
                    # (Nota: Algunos EPG lo tienen en la guía de programación)
                    if nombre:
                        # Por ahora creamos un mapa base sólido
                        nombre_norm = normalizar_texto(nombre)
                        mapping[nombre_norm] = nombre
                elem.clear()
    except Exception as e:
        print(f"⚠️ Nota: No pude leer todas las categorías del XML, usaré el Cerebro de Respaldo. Error: {e}")

    # CEREBRO DE RESPALDO (Diccionario Maestro por grupos)
    # Aquí ponemos los grupos grandes. Cualquier canal que se parezca a estos,
    # heredará su categoría automáticamente.
    DICCIONARIO_MAESTRO = {
        "DEPORTES": ["ESPN", "WIN SPORTS", "FOX SPORTS", "TYC", "GOLTV", "DIRECTV SPORTS", "NBA", "F1"],
        "CINE": ["HBO", "TNT", "AMC", "CINEMAX", "STAR CHANNEL", "GOLDEN", "CINE CANAL", "PARAMOUNT"],
        "CULTURA": ["DISCOVERY", "NATIONAL GEOGRAPHIC", "HISTORY", "ANIMAL PLANET", "ID"],
        "INFANTIL": ["DISNEY", "NICKELODEON", "CARTOON NETWORK", "DISCOVERY KIDS", "BOOMERANG"],
        "NOTICIAS": ["CNN", "BBC", "NTN24", "TELEVENTA", "DW", "EURONEWS"]
    }

    return DICCIONARIO_MAESTRO

MAPA_MAESTRO = construir_mapeo_categorias()
print("✅ El robot ha terminado de estudiar.")

import time

def inspeccionar_y_limpiar(canales, nombres_maestros):
    validos = []
    invalidos = []
    total = len(canales)

    # Cabeceras para que el servidor no nos bloquee
    headers = {'User-Agent': 'VLC/3.0.18'}

    print(f"🚀 Iniciando inspección de {total} canales...")

    for i, canal in enumerate(canales):
        nombre_original = canal['nombre_original']
        url = canal['url']

        # 1. EL EXAMEN (¿Funciona?)
        try:
            # Usamos stream=True para no descargar el video entero, solo ver si abre
            with requests.get(url, headers=headers, timeout=5, stream=True) as r:
                if r.status_code == 200:
                    estado = "✅ OK"

                    # 2. HOMOGENIZAR (Buscar nombre bonito)
                    # Comparamos el nombre original con los 26,000 nombres maestros
                    mejor_coincidencia, puntaje = process.extractOne(
                        nombre_original,
                        nombres_maestros,
                        scorer=fuzz.token_sort_ratio
                    )

                    # Si el parecido es mayor al 80%, usamos el nombre maestro
                    nombre_final = mejor_coincidencia if puntaje > 80 else nombre_original

                    validos.append({"nombre": nombre_final, "url": url})
                else:
                    estado = "❌ FAIL (Status)"
                    invalidos.append(canal)
        except:
            estado = "❌ FAIL (Timeout/Error)"
            invalidos.append(canal)

        # Reporte de progreso cada 10 canales para no llenar la pantalla
        if (i + 1) % 10 == 0 or i + 1 == total:
            print(f"Progreso: [{i + 1}/{total}] - {nombre_original} -> {estado}")

        # 3. PAUSA DE CORTESÍA (Para no ser bloqueados)
        time.sleep(0.5)

    return validos, invalidos

# ¡A trabajar!
CANALES_VALIDOS, CANALES_INVALIDOS = inspeccionar_y_limpiar(TODOS_LOS_CANALES, NOMBRES_MAESTROS)

print(f"\n--- RESULTADOS FINALES ---")
print(f"Canales que sirven: {len(CANALES_VALIDOS)}")
print(f"Canales rotos: {len(CANALES_INVALIDOS)}")

from google.colab import files

def guardar_y_descargar(canales_validos, nombre_archivo="lista_limpia.m3u"):
    if not canales_validos:
        print("❌ No hay canales válidos para guardar.")
        return

    print(f"📝 Escribiendo {len(canales_validos)} canales en el archivo...")

    with open(nombre_archivo, "w", encoding="utf-8") as f:
        # Escribimos la cabecera que todos los reproductores entienden
        f.write("#EXTM3U\n")

        for canal in canales_validos:
            # Escribimos el nombre arreglado y la URL
            f.write(f"#EXTINF:-1,{canal['nombre']}\n")
            f.write(f"{canal['url']}\n")

    print(f"✅ Archivo '{nombre_archivo}' creado con éxito.")

    # Este comando hace que tu navegador descargue el archivo
    files.download(nombre_archivo)

# Ejecutamos la entrega
guardar_y_descargar(CANALES_VALIDOS)

# 1. Aseguramos que la herramienta de limpieza esté instalada
!pip install unidecode
from unidecode import unidecode
import re

def limpieza_estilo_metadata(nombre):
    if not nombre: return ""
    nombre = unidecode(nombre).upper()
    # Limpieza de símbolos para que A&E sea A E y no se pierda
    nombre = nombre.replace("&AMP;", " ").replace("&", " ")

    ruido = [
        r'\.CO', r'\.UY', r'\.AR', r'\.FI', r'\.PH', r'\.HK', r'\.DE', r'\.PL',
        r'BANDA C', r'TRASN', r'BARRANCA', r'TRANS', r'HD', r'SD', r'4K', r'LATIN'
    ]
    for r_word in ruido:
        nombre = re.sub(r_word, '', nombre)

    return " ".join(re.sub(r'[^A-Z0-9 ]', ' ', nombre).split())

# 2. Diccionario con la nueva categoría MUSICA y ajustes de precisión
DICCIONARIO_CATEGORIAS = {
    "CINE": ["CANAL+","GOLDEN","HBO", "TNT", "AMC", "CINEMAX", "STAR", "GOLDEN", "CINECANAL", "PARAMOUNT", "STUDIO", "CINE", "A E",
             "DHE", "DE PELICULA", "AXN", "WARNER", "SONY", "UNIVERSAL","FX","FREE","FILM","MULTIPREMIER","SPACE"],
    "DEPORTES": ["ESPN", "WIN", "FOX SPORTS", "TYC", "GOL", "SPORT", "DIRECTV", "NBA", "F1", "AMERICA SPORTS", "VIA X ESPORTS"],
    "MUSICA": ["MTV", "HTV", "MUSICA", "SALSA", "REGGAETON", "ROMANTICA", "POPULAR", "RUMBA", "LA KALLE", "LATIN POP", "TROPICAL", "MERENGUE", "ZONA LATINA"],
    "NACIONALES": ["CARACOL", "RCN", "CITY TV", "CANAL 1", "CANAL UNO", "SEÑAL COLOMBIA", "TELECARIBE", "TELEPACIFICO","TELEANTIOQUIA","TELECAFE", "TELESISLAS"],
    "INFANTIL": ["DISNEY", "NICK", "CARTOON", "KIDS", "BABY", "TOON", "BOOMERANG", "INFANTIL", "DISCOVERY KIDS"],
    "NOTICIAS": ["CNN", "BBC", "NTN24", "NOTICIAS", "NEWS", "TELESUR", "DW", "CABLE", "TIEMPO"],
    "CULTURA": ["DISCOVERY", "NAT GEO", "HISTORY", "ANIMAL", "PLANET", "ID", "AGRO", "CULTURA"],
    "RELIGION": ["3ABN", "CRISTOVISION", "ENLACE", "BETHEL", "EWTN", "AVIVAMIENTO"]
}

def clasificar_con_logica_mejorada(canal_nombre):
    limpio = limpieza_estilo_metadata(canal_nombre)
    for cat, palabras in DICCIONARIO_CATEGORIAS.items():
        if any(p in limpio for p in palabras):
            return cat
    return "VARIADOS"

# 3. GENERACIÓN DE ARCHIVOS
print("📝 Generando archivos finales...")

# --- ARCHIVO 1: CANALES VÁLIDOS ---
with open("lista_final_perfecta.m3u", "w", encoding="utf-8") as f:
    f.write("#EXTM3U\n")
    for canal in CANALES_VALIDOS:
        cat = clasificar_con_logica_mejorada(canal['nombre'])
        f.write(f'#EXTINF:-1 group-title="{cat}",{canal["nombre"]}\n')
        f.write(f"{canal['url']}\n")

# --- ARCHIVO 2: CANALES INVÁLIDOS (LOS QUE FALLARON) ---
with open("canales_invalidos.m3u", "w", encoding="utf-8") as f:
    f.write("#EXTM3U\n")
    f.write("# REPORTE DE CANALES QUE NO FUNCIONARON ESTA SEMANA\n")
    for canal in CANALES_INVALIDOS:
        f.write(f"#EXTINF:-1,{canal['nombre_original']}\n")
        f.write(f"{canal['url']}\n")

print(f"✅ ¡Todo listo!")
print(f"1. Canales funcionando: {len(CANALES_VALIDOS)} (en 'lista_final_perfecta.m3u')")
print(f"2. Canales rotos: {len(CANALES_INVALIDOS)} (en 'canales_invalidos.m3u')")

# 1. Aseguramos que la herramienta de limpieza esté instalada
!pip install unidecode
from unidecode import unidecode
import re

def limpieza_estilo_metadata(nombre):
    if not nombre: return ""
    nombre = unidecode(nombre).upper()
    # Limpieza de símbolos para que A&E sea A E y no se pierda
    nombre = nombre.replace("&AMP;", " ").replace("&", " ")

    ruido = [
        r'\.CO', r'\.UY', r'\.AR', r'\.FI', r'\.PH', r'\.HK', r'\.DE', r'\.PL',
        r'BANDA C', r'TRASN', r'BARRANCA', r'TRANS', r'HD', r'SD', r'4K', r'LATIN'
    ]
    for r_word in ruido:
        nombre = re.sub(r_word, '', nombre)

    return " ".join(re.sub(r'[^A-Z0-9 ]', ' ', nombre).split())

# 2. Diccionario con la nueva categoría MUSICA y ajustes de precisión
DICCIONARIO_CATEGORIAS = {
    "CINE": ["GOLDEN","HBO", "TNT", "AMC", "CINEMAX", "STAR", "GOLDEN", "CINECANAL", "PARAMOUNT", "STUDIO", "CINE", "A E",
             "DHE", "DE PELICULA", "AXN", "WARNER", "SONY", "UNIVERSAL","FX","FREE","FILM","MULTIPREMIER","SPACE"],
    "DEPORTES": ["ESPN", "WIN", "FOX SPORTS", "TYC", "GOL", "SPORT", "DIRECTV", "NBA", "F1", "AMERICA SPORTS", "VIA X ESPORTS"],
    "MUSICA": ["MTV", "HTV", "MUSICA", "SALSA", "REGGAETON", "ROMANTICA", "POPULAR", "RUMBA", "LA KALLE", "LATIN POP", "TROPICAL", "MERENGUE", "ZONA LATINA", "CAPITAL"],
    "NACIONALES": ["CARACOL", "RCN", "CITY TV", "CANAL 1", "CANAL UNO", "ESTRELLAS", "AZTECA", "AZ ", "AMERICA TV"],
    "INFANTIL": ["DISNEY", "NICK", "CARTOON", "KIDS", "BABY", "TOON", "BOOMERANG", "INFANTIL", "DISCOVERY KIDS"],
    "NOTICIAS": ["CNN", "BBC", "NTN24", "NOTICIAS", "NEWS", "TELESUR", "DW", "CABLE", "TIEMPO"],
    "CULTURA": ["DISCOVERY", "NAT GEO", "HISTORY", "ANIMAL", "PLANET", "ID", "AGRO", "CULTURA"],
    "RELIGION": ["3ABN", "CRISTOVISION", "ENLACE", "BETHEL", "EWTN", "AVIVAMIENTO"]
}

def clasificar_con_logica_mejorada(canal_nombre):
    limpio = limpieza_estilo_metadata(canal_nombre)
    for cat, palabras in DICCIONARIO_CATEGORIAS.items():
        if any(p in limpio for p in palabras):
            return cat
    return "VARIADOS"

# 3. GENERACIÓN DE ARCHIVOS
print("📝 Generando archivos finales...")

# --- ARCHIVO 1: CANALES VÁLIDOS ---
with open("lista_final_perfecta.m3u", "w", encoding="utf-8") as f:
    f.write("#EXTM3U\n")
    for canal in CANALES_VALIDOS:
        cat = clasificar_con_logica_mejorada(canal['nombre'])
        f.write(f'#EXTINF:-1 group-title="{cat}",{canal["nombre"]}\n')
        f.write(f"{canal['url']}\n")

# --- ARCHIVO 2: CANALES INVÁLIDOS (LOS QUE FALLARON) ---
with open("canales_invalidos.m3u", "w", encoding="utf-8") as f:
    f.write("#EXTM3U\n")
    f.write("# REPORTE DE CANALES QUE NO FUNCIONARON ESTA SEMANA\n")
    for canal in CANALES_INVALIDOS:
        f.write(f"#EXTINF:-1,{canal['nombre_original']}\n")
        f.write(f"{canal['url']}\n")

print(f"✅ ¡Todo listo!")
print(f"1. Canales funcionando: {len(CANALES_VALIDOS)} (en 'lista_final_perfecta.m3u')")
print(f"2. Canales rotos: {len(CANALES_INVALIDOS)} (en 'canales_invalidos.m3u')")