name: Actualizar Lista Semanal
on:
  schedule:
    - cron: '0 0 * * 0' # Se ejecuta todos los domingos a las 00:00 UTC
  workflow_dispatch: # Permite ejecución manual desde la pestaña Actions

permissions:
  contents: write # Permiso crucial para que el robot edite tus archivos TXT y M3U

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Silencia el warning de Node.js
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script de actualización
        run: python actualizar_lista.py

      - name: Sincronizar y Guardar cambios en GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Sincronizamos con la nube para evitar errores de "rejected"
          git pull origin main --rebase
          
          # Añadimos los 4 archivos clave al seguimiento
          git add lista_final_perfecta.m3u canales_invalidos.m3u servidores.txt servidores_out.txt
          
          # Guardamos los cambios (si los hay)
          git commit -m "Actualización automática: Listas y rastro de servidores" || echo "No se detectaron cambios"
          
          # Subimos todo al repositorio
          git push origin main
