name: Actualizar Lista Semanal

on:
  schedule:
    - cron: '0 0 * * 0' # Se ejecuta automáticamente todos los domingos a las 00:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

permissions:
  contents: write # Permite al robot modificar y guardar archivos en tu repositorio

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # Forzamos el uso de Node 24 para eliminar los avisos de depreciación
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      # Pasamos tus credenciales de correo desde Secrets al Script
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script de actualización
        run: python actualizar_lista.py

      - name: Sincronizar y Guardar cambios en GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 1. Nos aseguramos de estar al día con la nube para evitar errores de push
          git pull origin main --rebase
          
          # 2. Agregamos los archivos generados y actualizados
          git add lista_final_perfecta.m3u canales_invalidos.m3u servidores.txt servidores_out.txt
          
          # 3. Confirmamos los cambios (si no hay cambios, el script no fallará)
          git commit -m "Actualización automática: Listas, Historial y Alertas" || echo "No hay cambios para subir"
          
          # 4. Subimos los archivos finales a tu perfil
          git push origin main
