name: Prueba de Secretos
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Validar Secretos
        env:
          ID: ${{ secrets.TELEGRAM_API_ID }}
        run: |
          if [ -z "$ID" ]; then echo "Error: Secreto no configurado"; exit 1; else echo "Secreto detectado correctamente"; fi
